### ISSUE TITLE
Support returning a promise

### ISSUE THREAD

**Issue by adjohn** [iopipe/iopipe-js#42]
I'd like the ability to just return a promise instead of having to use a callback.

**Comment by mrickard** [comment]
Having dug into this and created a number of test-bench functions using promises...I think we actually do support it for most cases. If the return value of a user's wrapped function is a promise, they'll see metrics just fine.  I've reached out to the user to see if I understand their intended use correctly, but the test scenarios I've tried all return promises and provide our analytics.

**Comment by adjohn** [comment]
@mrickard is there anything special that needs to be done to support this?  If so, some examples in the examples repo would be great to see.

**Comment by mrickard** [comment]
@adjohn All of the tests I've run are using completely unaltered IOpipe-js, so I'd say nothing special, barring that caveat of some special use case. I'd be happy to throw together an example...or add to the instructions on the Install page. 

Another thing about the examples repo is that we're showing security warnings due to older dependencies.  I'm happy to take on updating those, if that's a reasonable priority.  (Short-term Picard fixing should probably go above that in priorities, though.)

**Comment by mrickard** [comment]
(Also, I see that the customer is on Slack, so I might hear an update to the DM thread.)
